{{ if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: cifar10-inference
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
{{ end }}
