{{ if .Values.mlflow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: {{ .Values.mlflow.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow-server
        image: {{ .Values.mlflow.server.image }}
        args:
        - mlflow
        - server
        - --backend-store-uri=postgresql://mlflow:mlflow@postgresql/mlflow
        - --default-artifact-root=s3://mlflow/
        - --host=0.0.0.0
        - --port={{ .Values.mlflow.server.trackingPort }}
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://minio:9000
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.mlflow.minio.accessKey }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.mlflow.minio.secretKey }}
        ports:
        - containerPort: {{ .Values.mlflow.server.trackingPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: {{ .Values.mlflow.namespace }}
spec:
  selector:
    app: mlflow-server
  ports:
    - port: {{ .Values.mlflow.server.trackingPort }}
{{ end }}
