{{ if .Values.protected.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.protected.minio.accessKey | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.protected.minio.secretKey | quote }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.protected.minio.endpoint | quote }}
  PUBLIC_KEY: {{ .Values.protected.publicKey | quote }}
{{ end }}
