apiVersion: v1
kind: PersistentVolume
metadata:
  name: kfp-artifacts-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/kfp-artifacts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kfp-artifacts-pvc
  namespace: kubeflow-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
