name: Sign Model
description: Signing the URI model with a private key
inputs:
  - {name: model_uri, type: String}
  - {name: private_key, type: String}
outputs:
  - {name: signature_file, type: String}
implementation:
  container:
    image: cifar10-gate4:latest
    command: [
      python, /app/sign_model.py,
      --private-key, {inputValue: private_key},
      --model-uri, {inputValue: model_uri},
      --output-signature, {outputPath: signature_file}
    ]
