name: Train CIFAR-10 with DP
description: Обучение CNN на CIFAR-10 с дифференциальной приватностью
inputs:
  - {name: data_path, type: String}
  - {name: epochs, type: Integer, default: '5'}
  - {name: batch_size, type: Integer, default: '64'}
  - {name: learning_rate, type: Float, default: '0.001'}
  - {name: noise_multiplier, type: Float, default: '1.0'}
  - {name: max_grad_norm, type: Float, default: '1.0'}
  - {name: delta, type: Float, default: '1e-5'}
outputs:
  - {name: model_uri, type: String}
  - {name: mlflow_run_id, type: String}
implementation:
  container:
    image: cifar10-train:latest
    env:
      MLFLOW_TRACKING_URI: http://mlflow-server.mlflow-system.svc.cluster.local:5000
    command: [
      python, /train.py,
      --data-path, {inputValue: data_path},
      --epochs, {inputValue: epochs},
      --batch-size, {inputValue: batch_size},
      --learning-rate, {inputValue: learning_rate},
      --enable-dp,
      --noise-multiplier, {inputValue: noise_multiplier},
      --max-grad-norm, {inputValue: max_grad_norm},
      --delta, {inputValue: delta}
    ]
