apiVersion: apps/v1
kind: Deployment
metadata:
  name: cifar10-tf-serving
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cifar10-tf-serving
  template:
    metadata:
      labels:
        app: cifar10-tf-serving
    spec:
      volumes:
      - name: model
        persistentVolumeClaim:
          claimName: model-pvc
      containers:
      - name: tf-serving
        image: tensorflow/serving:2.6.2
        ports:
        - containerPort: 8500
        - containerPort: 8501
        args:
        - "--model_base_path=/models"
        - "--model_name=cifar10"
        - "--rest_api_port=8501"
        volumeMounts:
        - name: model
          mountPath: /models
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        readinessProbe:
          httpGet:
            path: /v1/models/cifar10
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
