apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-minio-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mlflow-minio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-minio-pvc
  namespace: mlflow-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: mlflow-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: minioadmin
        - name: MINIO_ROOT_PASSWORD
          value: minioadmin
        ports:
        - containerPort: 9000
          name: minio
        - containerPort: 9001
          name: console
        volumeMounts:
        - name: minio-persistent-storage
          mountPath: /data
      volumes:
      - name: minio-persistent-storage
        persistentVolumeClaim:
          claimName: mlflow-minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: mlflow-system
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    name: minio
  - port: 9001
    targetPort: 9001
    name: console
  selector:
    app: minio
